export const ADD_TARGET = 'ADD_TARGET';
export const DELETE_TARGET = 'DELETE_TARGET';
export const GAME_START = 'GAME_START';
export const GAME_START_REQUESTED = 'GAME_START_REQUESTED';
export const GAME_STOP_REQUESTED ='GAME_STOP_REQUESTED';
export const UPDATE_TARGET = 'UPDATE_TARGET';
export const CLICK_TARGET = 'CLICK_TARGET';